### ISSUE TITLE
update conda repo with latest version of pysolr

### ISSUE THREAD

**Issue by Tagar** [conda-forge/pysolr-feedstock#6]
https://anaconda.org/conda-forge/pysolr 
shows latest version was updated 2.5 years ago..

Please update conda repo with latest version of pysolr

**Comment by dwervin** [comment]
Yeah, installing pysolr via conda FAILED due to this being toooo old.  What's up with this?  Error message says this version only good up to Python 3.6?

I thought Anaconda kept all of these packages updated so that folks using Anaconda Enterprise had the latest.  Seems that you all have dropped the ball.

**Comment by synapticarbors** [comment]
@dweervin -- I will update this package, but please note:

- These packages are created and maintained by the conda-forge project and not Anaconda
- This is a volunteer based organization, so please use a different tone or devote some of your own time to helping out.

**Comment by synapticarbors** [comment]
closed by #7

**Comment by dwervin** [comment]
Hmmm.....That's interesting.  When we talked to Anaconda about Anaconda Enterprise, they explained that they made sure these libraries are kept up-to-date at conda-forge.  They must have misrepresented that.

**Comment by synapticarbors** [comment]
I'm not sure what Anaconda said to you exactly, but Anaconda is involved in the maintenance of some feedstocks and they use the conda-forge recipes as a basis for some of their own builds, and they lend a substantial amount of know-how and time in their collaboration with conda-forge, but you can think of those as a subset of all of the packages on conda-forge. We rely on the time of volunteers to handle all of the rest.
